name: Build EXE

on:
    push

permissions:
  contents: write   # required to create releases / push tags
  packages: write   # required if you publish packages
  id-token: write   # only needed for OIDC flows; safe to keep if you use it

jobs:
    Build-Windows:
        runs-on: windows-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.12' # Update as needed

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt

          - name: Build EXE files
            run: python -m PyInstaller main.spec --noconfirm

          - name: Compile ISCC setup
            uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
            with:
                path: innosetup.iss

          - name: Archive Release
            uses: thedoctor0/zip-release@0.7.5
            with:
                type: 'zip'
                filename: 'tikzgraphgen-mobile.zip'
                directory: './dist/TikzGraphGen/'

          - name: Upload binaries to release
            uses: svenstaro/upload-release-action@v2
            with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: tikzgraphgen-mobile.zip
              asset_name: Version-mobile
              tag: ${{ github.ref }}
              overwrite: false
              body: "Release contain the mobile version for windows"

          - name: Upload EXEs as artifacts
            uses: actions/upload-artifact@v4
            with:
                name: exes-win
                path: dist/TikzGraphGen/

    Build-Linux:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10' # Update as needed

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt

          - name: Build EXE files
            run: python -m PyInstaller main.spec --noconfirm
            
          # - name: Upload files to Release
            # uses: actions/upload-release-asset@v1
            # env:
                # GITHUB_TOKEN: ${{ github.token }}
            # with:
                # upload_url: ${{ steps.create_release.outputs.upload_url }}
                # asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
                # asset_name: azblogfilter.linux-amd64.tar.gz
                # asset_content_type: application/gzip
            
          #- name: Print directory structure
          #  run: |
          #      cd ./dist/TikzGraphGen
          #      ls -a

          - name: Upload EXEs as artifacts
            uses: actions/upload-artifact@v4
            with:
                name: exes-debian
                path: dist/TikzGraphGen/

    # Publish files to Release:
        # runs-on: ubuntu-latest
        # steps:
          # - name: Checkout code
            # uses: actions/checkout@v4
            
          # - name: upload linux artifact
            # uses: actions/upload-release-asset@v1
            # env:
                # GITHUB_TOKEN: ${{ github.token }}
            # with:
                # upload_url: ${{ steps.create_release.outputs.upload_url }}
                # asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
                # asset_name: azblogfilter.linux-amd64.tar.gz
                # asset_content_type: application/gzip

          # - name: upload windows artifact
            # uses: actions/upload-release-asset@v1
            # env:
                # GITHUB_TOKEN: ${{ github.token }}
            # with:
                # upload_url: ${{ steps.create_release.outputs.upload_url }}
                # asset_path: ./bin/azblogfilter.windows-amd64.zip
                # asset_name: azblogfilter.windows-amd64.zip
                # asset_content_type: application/zip
